### ISSUE TITLE
Usage with Yarn

### ISSUE THREAD

**Issue by hassankhan** [craftship/yith-deprecated#26]
Just wondering, does Yith work with Yarn yet? Or does Yarn still not yet support private packages? Would love to give this a go if it is possible :smile:

**Comment by jonsharratt** [comment]
Heya, I am looking to firm everything up over the next week or so, currently spiking through to get main use case fleshed out with npm.

Now API Gateway, Serverless & Lambdas have moved on a lot to get to a version 1.0.0 I am looking to get things firmed up with full test coverage.

As part of this I will be setting up integration tests that will include yarn, will keep you posted with results as I get them, right now I can not confirm it will work just now 🙈

**Comment by jonsharratt** [comment]
Will do some tests this evening for yarn and let you know results in the meantime the repo has been refreshed with all the latest and greatest functionallity from Serverless, Lambdas and API Gateway.

The main thing is it is so much easier to get setup, no config files required, just set some environment variables and use the Serverless CLI to install and deploy.

https://github.com/craftship/yith

**Comment by hassankhan** [comment]
You're a legend, thanks!!
